# Generated by Django 5.1.2 on 2025-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('picture', models.URLField(blank=True, null=True)),
                ('isSuperAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
