# Generated by Django 5.1.2 on 2025-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0003_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
