# Generated by Django 5.1.2 on 2025-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0004_alter_admin_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
