# Generated by Django 5.1.2 on 2025-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0005_admin_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default=0, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
