# Generated by Django 5.1.2 on 2025-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0006_admin_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='civilite',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme')], default='Mr', max_length=3),
        ),
    ]
