# Generated by Django 5.1.2 on 2025-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0007_admin_civilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('school_year', models.CharField(max_length=9)),
                ('responsable_nom', models.CharField(max_length=100)),
                ('responsable_prenom', models.CharField(max_length=100)),
                ('responsable_lien', models.CharField(max_length=50)),
                ('responsable_email', models.EmailField(max_length=254)),
                ('responsable_telephone', models.CharField(max_length=20)),
                ('eleve_prenom', models.CharField(max_length=100)),
                ('eleve_nom', models.CharField(max_length=100)),
                ('eleve_date_naissance', models.DateField()),
                ('niveau_scolaire', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=20)),
                ('institut', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=100)),
            ],
        ),
    ]
