# Generated by Django 5.1.2 on 2025-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0008_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='institut',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
