# Generated by Django 5.1.2 on 2025-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0009_alter_inscription_classe_alter_inscription_institut'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscription',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
