# Generated by Django 5.1.2 on 2025-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0010_inscription_confirmed_inscription_confirmed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_by', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('news_date', models.DateField()),
                ('tag', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('article', models.TextField()),
                ('school_year', models.CharField(max_length=9)),
                ('is_pinned', models.BooleanField(default=False)),
                ('img_url', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-publish_date'],
            },
        ),
    ]
