# Generated by Django 5.1.2 on 2025-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0011_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
