# Generated by Django 5.1.2 on 2025-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0012_alter_news_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
