# Generated by Django 5.1.2 on 2025-05-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0013_alter_news_description_alter_news_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cvLink', models.URLField()),
                ('dateApply', models.DateField()),
            ],
        ),
    ]
