# Generated by Django 5.1.2 on 2025-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0014_condidats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
