# Generated by Django 5.1.2 on 2025-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0015_newsletteremails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
