# Generated by Django 5.1.2 on 2025-06-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0016_alter_inscription_responsable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='province',
        ),
    ]
