# Generated by Django 5.1.2 on 2025-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0017_remove_inscription_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='province',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
