# Generated by Django 5.1.2 on 2025-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0019_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='id',
        ),
        migrations.AddField(
            model_name='contactform',
            name='message_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
