# Generated by Django 5.1.2 on 2025-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_api', '0020_remove_contactform_id_contactform_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='message_id',
        ),
        migrations.AddField(
            model_name='contactform',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
